# build 
FROM node:18-alpine as build

COPY ./client/ /app
WORKDIR /app

RUN npm install --save-dev
RUN npm run build

# serve via nginx
FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
