# coding: utf-8

"""
    Elysia Documentation

    Development documentation  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.auth_aggie_body1 import AuthAggieBody1  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthAggieBody1(unittest.TestCase):
    """AuthAggieBody1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthAggieBody1(self):
        """Test AuthAggieBody1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.auth_aggie_body1.AuthAggieBody1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
