# coding: utf-8

"""
    Elysia Documentation

    Development documentation  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_grid_by_id(self):
        """Test case for delete_grid_by_id

        """
        pass

    def test_get_auth_aggie_auth_callback(self):
        """Test case for get_auth_aggie_auth_callback

        """
        pass

    def test_get_auth_logout(self):
        """Test case for get_auth_logout

        """
        pass

    def test_get_auth_me(self):
        """Test case for get_auth_me

        """
        pass

    def test_get_grid_by_id(self):
        """Test case for get_grid_by_id

        """
        pass

    def test_get_grid_list(self):
        """Test case for get_grid_list

        """
        pass

    def test_get_grid_snapshot_by_id(self):
        """Test case for get_grid_snapshot_by_id

        """
        pass

    def test_post_auth_aggie(self):
        """Test case for post_auth_aggie

        """
        pass

    def test_post_grid(self):
        """Test case for post_grid

        """
        pass

    def test_post_grid_by_id_pixel(self):
        """Test case for post_grid_by_id_pixel

        """
        pass

    def test_put_grid_by_id(self):
        """Test case for put_grid_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
