# coding: utf-8

"""
    Elysia Documentation

    Development documentation  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.id_pixel_body1 import IdPixelBody1  # noqa: E501
from swagger_client.rest import ApiException


class TestIdPixelBody1(unittest.TestCase):
    """IdPixelBody1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdPixelBody1(self):
        """Test IdPixelBody1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.id_pixel_body1.IdPixelBody1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
