# coding: utf-8

"""
    Elysia Documentation

    Development documentation  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.grid_body2 import GridBody2  # noqa: E501
from swagger_client.rest import ApiException


class TestGridBody2(unittest.TestCase):
    """GridBody2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGridBody2(self):
        """Test GridBody2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.grid_body2.GridBody2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
